### ISSUE TITLE
Not sorting properly

### ISSUE THREAD

**Issue by cheekEprogrammer** [dy/sort-ids#3]
Hello there, I was trying to find a package/way to sort an array of floats. The code in the npm example is wrong and breaks when you try to run. The variable for the sort is spelled wrong.

When I run the following example code, it does not work.

`var rates = [0.5458984375, 0.58251953125, 0.7080078125, 0.90087890625]
var names = ['John', 'Alexa', 'Jimmy', 'Kate']

var ids = sortIds(rates)`

i get an array returned of [3, 1, 2, 3]. its not sorting the first element of the array correctly. not sure whats going on but i cant use this package as intended.

**Comment by dy** [comment]
Not sure what you're talking about - example from readme works correctly without errors.
Your example as well: https://codesandbox.io/s/eloquent-dan-vpk2f9?file=/src/index.js
Anyways, just updated to v3. Can try again.
